/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StatsImport } from './routes/stats'
import { Route as SalesImport } from './routes/sales'
import { Route as ProjectImport } from './routes/project'
import { Route as CampaignImport } from './routes/campaign'
import { Route as BaseImport } from './routes/base'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StatsRoute = StatsImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRoute,
} as any)

const SalesRoute = SalesImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRoute,
} as any)

const ProjectRoute = ProjectImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRoute,
} as any)

const CampaignRoute = CampaignImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRoute,
} as any)

const BaseRoute = BaseImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/base': {
      id: '/base'
      path: '/base'
      fullPath: '/base'
      preLoaderRoute: typeof BaseImport
      parentRoute: typeof rootRoute
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignImport
      parentRoute: typeof rootRoute
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectImport
      parentRoute: typeof rootRoute
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesImport
      parentRoute: typeof rootRoute
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base': typeof BaseRoute
  '/campaign': typeof CampaignRoute
  '/project': typeof ProjectRoute
  '/sales': typeof SalesRoute
  '/stats': typeof StatsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base': typeof BaseRoute
  '/campaign': typeof CampaignRoute
  '/project': typeof ProjectRoute
  '/sales': typeof SalesRoute
  '/stats': typeof StatsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/base': typeof BaseRoute
  '/campaign': typeof CampaignRoute
  '/project': typeof ProjectRoute
  '/sales': typeof SalesRoute
  '/stats': typeof StatsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/base' | '/campaign' | '/project' | '/sales' | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/base' | '/campaign' | '/project' | '/sales' | '/stats'
  id:
    | '__root__'
    | '/'
    | '/base'
    | '/campaign'
    | '/project'
    | '/sales'
    | '/stats'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaseRoute: typeof BaseRoute
  CampaignRoute: typeof CampaignRoute
  ProjectRoute: typeof ProjectRoute
  SalesRoute: typeof SalesRoute
  StatsRoute: typeof StatsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaseRoute: BaseRoute,
  CampaignRoute: CampaignRoute,
  ProjectRoute: ProjectRoute,
  SalesRoute: SalesRoute,
  StatsRoute: StatsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/base",
        "/campaign",
        "/project",
        "/sales",
        "/stats"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/base": {
      "filePath": "base.tsx"
    },
    "/campaign": {
      "filePath": "campaign.tsx"
    },
    "/project": {
      "filePath": "project.tsx"
    },
    "/sales": {
      "filePath": "sales.tsx"
    },
    "/stats": {
      "filePath": "stats.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
